name: Dummy Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Simulate Deployment
      run: echo "Deploying to environment..."
    - name: Success Message
      run: echo "Deployment successful!"

